### ISSUE TITLE
额外发布附带运行库的版本

### ISSUE THREAD

**Issue by Doddddd** [ArakawaHenri/EnergyStarX#4]

**Comment by ArakawaHenri** [comment]
首先感谢您的关注。
MSIX 的版本是 Self Contained 的， 考虑到附带运行库会导致在已经安装有 .Net Runtime 的电脑上产生冗余，所以 Unpackaged 版本大概依然会以 Framework dependent 的形式发布。

**Comment by Doddddd** [comment]
> 首先感谢您的关注。
> MSIX 的版本是 Self Contained 的， 考虑到附带运行库会导致在已经安装有 .Net Runtime 的电脑上产生冗余，所以 Unpackaged 版本大概依然会以 Framework dependent 的形式发布。

感谢您的回复
