### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by ghost** [ArakawaHenri/EnergyStarX#6]
### 复现步骤 / Step to reproduce

系统版本：Edition	Windows 11 Pro for Workstations
Version	22H2
Installed on	‎9/‎27/‎2022
OS build	22621.521
Experience	Windows Feature Experience Pack 1000.22634.1000.0

具体情况：开机自启后有一定概率energy star x会自动在后台闪退，但是若使用energy star不会，不知道是不是版本问题。

### 预期行为 / Expected behaviour

应当在后台保持

### 实际行为 / Actual Behaviour

开机自启后有一定概率energy star x会自动在后台闪退，但是若使用energy star不会

### EnergyStarX 版本号 / EnergyStarX version code

0.3.4.0

### Windows 系统版本 / Windows version

Windows 11 Pro for Workstations Version	22H2 Installed on	‎9/‎27/‎2022 OS build	22621.521 Experience	Windows Feature Experience Pack 1000.22634.1000.0

### CPU 型号 / CPU model

R7 6800H

### 检查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/ArakawaHenri/EnergyStarX/issues)，并没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/ArakawaHenri/EnergyStarX/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs

**Comment by ShiSheng233** [comment]
我们近期会加上记录log的功能，届时若会再次复现，请携log继续comment

**Comment by ghost** [comment]
> 我们近期会加上记录 log 的功能，届时若会再次复现，请携 log 继续 comment
好的谢谢

**Comment by ShiSheng233** [comment]
> 0.3.4.0

Hmmmm 你用的是不是 [JasonWei512/EnergyStarX](https://github.com/JasonWei512/EnergyStarX) 这个repo的
我们没有发布过0.3.4.0

**Comment by JasonWei512** [comment]
是不是商店更新应用时把应用杀了
